Image reading in src/imginputfileconn.h (OpenCV 3.0)
Prior to change, at compilation

.build_release/lib/libcaffe.so: undefined reference to `cv::imread(cv::String const&, int)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imencode(cv::String const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::imdecode(cv::_InputArray const&, int)'

Local OpenCV version is 3.0, where macros have changed from - supposedly - rep version (2.4; CV_LOAD_IMAGE_* to IMREAD_*)